name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup OpenHarmony SDK
        uses: openharmony-rs/setup-ohos-sdk@main
        with:
          version: '5.1.0'
          fixup-path: true
      - name: Cache arkui-x
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/arkui-x
          key: "arkui-x"
      - name: Setup arkui-x
        run: |
          export ARKUIX_SDK_HOME=$HOME/arkui-x
          mkdir -p $ARKUIX_SDK_HOME/licenses
          cp -r .ci/* $ARKUIX_SDK_HOME/licenses
          echo "ARKUIX_SDK_HOME=$HOME/arkui-x" >> $GITHUB_ENV
      - name: Setup hvigor
        run: |
          echo "@ohos:registry=https://repo.harmonyos.com/npm/" >> ~/.npmrc
          npm install @ohos/hvigor
          npm install @ohos/hvigor-ohos-plugin
          npm install @ohos/hvigor-ohos-arkui-x-plugin
          npm list
      - name: Build
        run: |
          node ./node_modules/@ohos/hvigor/bin/hvigor.js -p product=ohos assembleHap
      - uses: actions/upload-artifact@v4
        with:
          name: hap
          path: entry/build/ohos/outputs/default/entry-default-unsigned.hap
