name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup OpenHarmony SDK
        uses: openharmony-rs/setup-ohos-sdk@v0.2.0
      - name: Move OpenHarmony SDK
        run: |
          mkdir -p $OHOS_BASE_SDK_HOME/13
          mv $OHOS_BASE_SDK_HOME/{ets,js,native,previewer,toolchains} $OHOS_BASE_SDK_HOME/13
          mkdir -p $OHOS_BASE_SDK_HOME/licenses
          cp -r .ci/* $OHOS_BASE_SDK_HOME/licenses
      - name: Setup arkui-x
        run: |
          export ARKUIX_SDK_HOME=$HOME/arkui-x
          mkdir -p $ARKUIX_SDK_HOME/licenses
          cp -r .ci/* $ARKUIX_SDK_HOME/licenses
          echo "ARKUIX_SDK_HOME=$HOME/arkui-x" >> $GITHUB_ENV
      - name: Setup hvigor
        run: |
          echo "@ohos:registry=https://repo.harmonyos.com/npm/" >> ~/.npmrc
          npm install @ohos/hvigor
          npm install @ohos/hvigor-ohos-plugin
          npm install @ohos/hvigor-ohos-arkui-x-plugin
      - name: Build
        run: |
          node ./node_modules/@ohos/hvigor/bin/hvigor.js -p product=ohos assembleHap
